### ISSUE TITLE
ImportError: No module named _add_two_ints_wrapper_cpp

### ISSUE THREAD

**Issue by sarathjayanthan** [galou/python_bindings_tutorial#1]
Hello,

I am trying to use these packages as per the ROS Wiki Tutorial. I have made a test.py node with the below code:
`  #!/usr/bin/env python 
   import rospy
   from std_msgs.msg import Int64
   from python_bindings_tutorial import AddTwoInts
   a = Int64(4)
   b = Int64(2)
   addtwoints = AddTwoInts()
   sum = addtwoints.add(a, b)
   sum`

When I am trying to run test.py, I am getting the following error : 
`Traceback (most recent call last):
  File "/home/pi/python_bindings_ws/src/python_bindings_tutorial-master/src/test.py", line 4, in <module>
    from python_bindings_tutorial import AddTwoInts
  File "/home/pi/python_bindings_ws/src/python_bindings_tutorial-master/src/python_bindings_tutorial/__init__.py", line 1, in <module>
    from python_bindings_tutorial._add_two_ints_wrapper_py import AddTwoInts
  File "/home/pi/python_bindings_ws/src/python_bindings_tutorial-master/src/python_bindings_tutorial/_add_two_ints_wrapper_py.py", line 6, in <module>
    from python_bindings_tutorial._add_two_ints_wrapper_cpp import AddTwoIntsWrapper
ImportError: No module named _add_two_ints_wrapper_cpp
`
 Could someone help me solve this issue?

Thanks in advance.

**Comment by Matt-Galinski** [comment]
go to your catkin_ws directory and run: 
`catkin_make`
It build the code in python_bindings_tutorial directory, after what you will be able to run the import command in your python script.

**Comment by galou** [comment]
@sarathjayanthan Does it solve your issue? If yes, please close this issue.

@Matt-Galinski: thanks!
